### ISSUE TITLE
Subscribers receive too much emails

### ISSUE THREAD

**Issue by friponneau** [andygrunwald/cachet#3]
The context is:
 - A cachet page that monitors the state of a service.  
 - The service availability is verified every 10 minutes, and the cachet component is updated with the value.
 - Subscribers want to be warned whenever the service changes state.

Currently, the user is warned whenever the component state is updated, regardless of the value.

Solution: send notification email only when new information is available (for example: the component state is updated with a different status than the current one).

Workaround: update the component only when the value has actually changed.  The problem with this is that the person looking at the component has no way of knowing the state of the service was actually monitored.

**Comment by andygrunwald** [comment]
Thanks. But this looks like a new feature request for cachet itself.
