### ISSUE TITLE
Subscribers retain their component subscription

### ISSUE THREAD

**Issue by friponneau** [andygrunwald/cachet#4]
If I subscribe an email, un-subscribe it, then subscribe it again, I'm registered twice every for components.

Here's an excerpt of the metrics that are sent back.  Please note that the "subscriptions" array has several entries with the same "component_id".

 {
      "id": 2,
      "email": "xxxx@hotmail.com",
      "verify_code": "xxxx",
      "verified_at": "Monday 16th January 2017 09:48:41",
      "created_at": "2017-01-16 09:47:39",
      "updated_at": "2017-01-16 09:48:41",
      "global": true,
      "subscriptions": [
        {
          "id": 21,
          "subscriber_id": 2,
          "component_id": 1,
          "created_at": "2017-01-16 14:36:46",
          "updated_at": "2017-01-16 14:36:46"
        },
        {
          "id": 22,
          "subscriber_id": 2,
          "component_id": 2,
          "created_at": "2017-01-16 14:36:46",
          "updated_at": "2017-01-16 14:36:46"
        },
        {
          "id": 23,
          "subscriber_id": 2,
          "component_id": 3,
          "created_at": "2017-01-16 14:36:46",
          "updated_at": "2017-01-16 14:36:46"
        },
        {
          "id": 24,
          "subscriber_id": 2,
          "component_id": 4,
          "created_at": "2017-01-16 14:36:46",
          "updated_at": "2017-01-16 14:36:46"
        },
        {
          "id": 25,
          "subscriber_id": 2,
          "component_id": 1,
          "created_at": "2017-01-16 14:38:35",
          "updated_at": "2017-01-16 14:38:35"
        },
        {
          "id": 26,
          "subscriber_id": 2,
          "component_id": 2,
          "created_at": "2017-01-16 14:38:35",
          "updated_at": "2017-01-16 14:38:35"
        },
        {
          "id": 27,
          "subscriber_id": 2,
          "component_id": 3,
          "created_at": "2017-01-16 14:38:35",
          "updated_at": "2017-01-16 14:38:35"
        },
        {
          "id": 28,
          "subscriber_id": 2,
          "component_id": 4,
          "created_at": "2017-01-16 14:38:35",
          "updated_at": "2017-01-16 14:38:35"
        },
        {
          "id": 29,
          "subscriber_id": 2,
          "component_id": 1,
          "created_at": "2017-01-16 14:47:39",
          "updated_at": "2017-01-16 14:47:39"
        },
        {
          "id": 30,
          "subscriber_id": 2,
          "component_id": 2,
          "created_at": "2017-01-16 14:47:39",
          "updated_at": "2017-01-16 14:47:39"
        },
        {
          "id": 31,
          "subscriber_id": 2,
          "component_id": 3,
          "created_at": "2017-01-16 14:47:39",
          "updated_at": "2017-01-16 14:47:39"
        },
        {
          "id": 32,
          "subscriber_id": 2,
          "component_id": 4,
          "created_at": "2017-01-16 14:47:39",
          "updated_at": "2017-01-16 14:47:39"
        }
      ]
    }

Also, you can see the problem in the subscribers page (see attached file)

![cachetbug](https://cloud.githubusercontent.com/assets/3298261/21993934/54693b52-dbeb-11e6-96f5-bd00a2719497.jpg)

**Comment by andygrunwald** [comment]
Hey @friponneau,
i guess this is an issue from cachet itself. I guess this is the reason why you posted it here: https://github.com/CachetHQ/Cachet/issues/2315
And closed this issue right away?

**Comment by friponneau** [comment]
Yeah, sorry, I opened my issues on the wrong repo, closed them and reopened them in the right place.  Again, sorry for that...

débé
---
Envoyé d'un appareil mobile de la main gauche en roulant à vive allure en moto sur un sentier empierré: veuillez excuser les fautes.

________________________________
